/* THIS (.ts) FILE IS GENERATED BY Tapper */
/* eslint-disable */
/* tslint:disable */

/** Transpiled from HypeProxy.Responses.Insights.PingResponse */
export type PingResponse = {
    /** Transpiled from bool */
    isOperational: boolean;
    /** Transpiled from int */
    reason: number;
    /** Transpiled from long */
    elapsedMilliseconds: number;
}

