/* THIS (.ts) FILE IS GENERATED BY Tapper */
/* eslint-disable */
/* tslint:disable */
import { RequestDetails } from './HypeProxy.Responses';

/** Transpiled from HypeProxy.Responses.ApiResponse.ApiError */
export type ApiError = {
    /** Transpiled from HypeProxy.Responses.ApiResponse.ApiErrorCode */
    code?: ApiErrorCode;
    /** Transpiled from string */
    description?: string;
}

/** Transpiled from HypeProxy.Responses.ApiResponse.ApiErrorCode */
export type ApiErrorCode = {
}

/** Transpiled from HypeProxy.Responses.ApiResponse.ApiResponse */
export type ApiResponse = {
    /** Transpiled from string */
    message?: string;
    /** Transpiled from int */
    statusCode: number;
    /** Transpiled from object */
    data?: any;
    /** Transpiled from System.Collections.Generic.IEnumerable<HypeProxy.Responses.ApiResponse.ApiError> */
    errors?: ApiError[];
    /** Transpiled from HypeProxy.Responses.RequestDetails */
    requestDetails?: RequestDetails;
}

