/* THIS (.ts) FILE IS GENERATED BY Tapper */
/* eslint-disable */
/* tslint:disable */
import { PaymentMethods, BillingCycles } from './HypeProxy.Constants';
import { Product, Location, Provider, BaseEntity } from './HypeProxy.Entities';

/** Transpiled from HypeProxy.Entities.Prices.Price */
export type Price = {
    /** Transpiled from HypeProxy.Constants.PaymentMethods */
    paymentMethod: PaymentMethods;
    /** Transpiled from HypeProxy.Constants.BillingCycles */
    billingCycle: BillingCycles;
    /** Transpiled from bool */
    isAutomaticRenewEnabled: boolean;
    /** Transpiled from double */
    unitPrice: number;
    /** Transpiled from string? */
    planId?: string;
    /** Transpiled from System.Guid */
    productId: string;
    /** Transpiled from System.Guid */
    locationId?: string;
    /** Transpiled from System.Guid */
    providerId?: string;
    /** Transpiled from HypeProxy.Entities.Product */
    product: Product;
    /** Transpiled from HypeProxy.Entities.Location? */
    location?: Location;
    /** Transpiled from HypeProxy.Entities.Provider? */
    provider?: Provider;
    /** Transpiled from System.Collections.Generic.ICollection<HypeProxy.Entities.Prices.PriceTier>? */
    priceTiers?: PriceTier[];
} & BaseEntity;

/** Transpiled from HypeProxy.Entities.Prices.PriceTier */
export type PriceTier = {
    /** Transpiled from System.Guid */
    id: string;
    /** Transpiled from int */
    volumeThreshold: number;
    /** Transpiled from bool */
    isInclusiveThreshold?: boolean;
    /** Transpiled from double */
    unitPrice: number;
    /** Transpiled from System.Guid */
    priceId: string;
    /** Transpiled from HypeProxy.Entities.Prices.Price */
    price: Price;
}

