/* THIS (.ts) FILE IS GENERATED BY Tapper */
/* eslint-disable */
/* tslint:disable */
import { LocationDetails } from './HypeProxy.Responses.InsightsSummary';

/** Transpiled from HypeProxy.Responses.Insights.LogLine */
export type LogLine = {
    /** Transpiled from System.DateTime */
    dateTime: (Date | string);
    /** Transpiled from string */
    serviceName?: string;
    /** Transpiled from int */
    errorCode: number;
    /** Transpiled from string */
    clientEndpoint?: string;
    /** Transpiled from string */
    targetEndpoint?: string;
    /** Transpiled from HypeProxy.Responses.InsightsSummary.LocationDetails */
    clientLocation?: LocationDetails;
    /** Transpiled from HypeProxy.Responses.InsightsSummary.LocationDetails */
    targetLocation?: LocationDetails;
    /** Transpiled from string */
    httpMethod?: string;
    /** Transpiled from string */
    url?: string;
    /** Transpiled from long */
    receivedBytes: number;
}

/** Transpiled from HypeProxy.Responses.Insights.PingResponse */
export type PingResponse = {
    /** Transpiled from bool */
    isOperational: boolean;
    /** Transpiled from int */
    reason: number;
    /** Transpiled from long */
    elapsedMilliseconds: number;
}

