/* THIS (.ts) FILE IS GENERATED BY Tapper */
/* eslint-disable */
/* tslint:disable */
import { Product, Location } from './HypeProxy.Entities';
import { Proxy } from './HypeProxy.Entities.Proxies';
import { BaseEntity } from './HypeProxy.Infrastructure.Entities';

/** Transpiled from HypeProxy.Entities.Infrastructure.Bay */
export type Bay = {
    /** Transpiled from string */
    name: string;
    /** Transpiled from int */
    stages?: number;
    /** Transpiled from int */
    size?: number;
    /** Transpiled from bool */
    isOperational: boolean;
    /** Transpiled from System.Guid */
    datacenterId: string;
} & BaseEntity;

/** Transpiled from HypeProxy.Entities.Infrastructure.ComputeUnit */
export type ComputeUnit = {
    /** Transpiled from string */
    name: string;
    /** Transpiled from System.Guid */
    productId: string;
    /** Transpiled from System.Guid */
    bayId?: string;
} & BaseEntity;

/** Transpiled from HypeProxy.Entities.Infrastructure.Datacenter */
export type Datacenter = {
    /** Transpiled from string */
    name: string;
    /** Transpiled from string? */
    description?: string;
    /** Transpiled from int */
    capacity?: number;
    /** Transpiled from bool */
    isOperational: boolean;
    /** Transpiled from bool */
    isTemporary: boolean;
    /** Transpiled from System.Guid */
    locationId: string;
} & BaseEntity;

