/* THIS (.ts) FILE IS GENERATED BY Tapper */
/* eslint-disable */
/* tslint:disable */
import { Proxy } from './HypeProxy.Entities.Proxies';

/** Transpiled from HypeProxy.Entities.Features.IpRotation */
export type IpRotation = {
    /** Transpiled from int */
    interval: number;
}

