/* THIS (.ts) FILE IS GENERATED BY Tapper */
/* eslint-disable */
/* tslint:disable */
import { WarningLevels } from './HypeProxy.Constants';
import { BaseEntityWithOwnership } from './HypeProxy.Entities';

/** Transpiled from HypeProxy.Entities.Statuses.RequestDetail */
export type RequestDetail = {
    /** Transpiled from string? */
    endpoint?: string;
    /** Transpiled from long */
    timestamp: number;
}

/** Transpiled from HypeProxy.Entities.Statuses.Status */
export type Status = {
    /** Transpiled from string? */
    title?: string;
    /** Transpiled from string? */
    message?: string;
    /** Transpiled from string */
    icon: string;
    /** Transpiled from HypeProxy.Constants.WarningLevels */
    level: WarningLevels;
    /** Transpiled from bool */
    isAdministrator: boolean;
    /** Transpiled from System.Guid */
    relatedEntity?: string;
    /** Transpiled from string? */
    relatedEntityType?: string;
} & BaseEntityWithOwnership;

