/* THIS (.ts) FILE IS GENERATED BY Tapper */
/* eslint-disable */
/* tslint:disable */
import { ApiError } from './HypeProxy.Errors';
import { RequestDetails } from './HypeProxy.Requests';
import { LocationDetails } from './HypeProxy.DataModels';
import { AuthorizationDetails } from './HypeProxy.Entities.ApplicationUsers';

/** Transpiled from HypeProxy.Responses.ApiKeyResponse */
export type ApiKeyResponse = {
    /** Transpiled from System.Guid */
    userId: string;
    /** Transpiled from string */
    token?: string;
    /** Transpiled from System.DateTime */
    tokenExpiration?: (Date | string);
}

/** Transpiled from HypeProxy.Responses.ApiResponse */
export type ApiResponse = {
    /** Transpiled from string */
    message?: string;
    /** Transpiled from int */
    statusCode: number;
    /** Transpiled from object */
    data?: any;
    /** Transpiled from System.Collections.Generic.IEnumerable<HypeProxy.Errors.ApiError> */
    errors?: ApiError[];
    /** Transpiled from HypeProxy.Requests.RequestDetails */
    requestDetails?: RequestDetails;
}

/** Transpiled from HypeProxy.Responses.InsightsSummaryResponse */
export type InsightsSummaryResponse = {
    /** Transpiled from string */
    remoteIp?: string;
    /** Transpiled from string */
    internetServiceProvider?: string;
    /** Transpiled from string */
    asn?: string;
    /** Transpiled from int */
    trustScore: number;
    /** Transpiled from HypeProxy.DataModels.LocationDetails */
    geolocationDetails?: LocationDetails;
}

/** Transpiled from HypeProxy.Responses.OrderSummaryResponse */
export type OrderSummaryResponse = {
    /** Transpiled from string */
    details?: string;
    /** Transpiled from double */
    unitPrice: number;
    /** Transpiled from double */
    vatAmount?: number;
    /** Transpiled from double */
    subtotalAmount: number;
    /** Transpiled from double */
    totalAmount: number;
    /** Transpiled from string? */
    couponCode?: string;
    /** Transpiled from double */
    priceOff?: number;
    /** Transpiled from double */
    percentOff?: number;
    /** Transpiled from int */
    availableStockForCriteria: number;
}

/** Transpiled from HypeProxy.Responses.PaymentResponse */
export type PaymentResponse = {
    /** Transpiled from System.Uri */
    returnUrl?: string;
    /** Transpiled from object */
    customData?: any;
}

/** Transpiled from HypeProxy.Responses.PingResponse */
export type PingResponse = {
    /** Transpiled from bool */
    isOperational: boolean;
    /** Transpiled from int */
    reason: number;
    /** Transpiled from long */
    elapsedMilliseconds: number;
}

/** Transpiled from HypeProxy.Responses.UserRequirementsResponse */
export type UserRequirementsResponse = {
    /** Transpiled from System.Guid */
    id: string;
    /** Transpiled from bool */
    hadFirstLogin: boolean;
    /** Transpiled from bool */
    requireOnboarding: boolean;
    /** Transpiled from bool */
    requireKyc: boolean;
    /** Transpiled from bool */
    hasConfirmedEmail: boolean;
    /** Transpiled from bool */
    hasDefinedBillingDetails: boolean;
    /** Transpiled from bool */
    hasDefinedUsageExplanation: boolean;
    /** Transpiled from bool */
    hasAppliedKyc: boolean;
}

/** Transpiled from HypeProxy.Responses.UserSummaryResponse */
export type UserSummaryResponse = {
    /** Transpiled from System.Guid */
    userId: string;
    /** Transpiled from string */
    fullName?: string;
    /** Transpiled from string */
    avatar?: string;
    /** Transpiled from long */
    monthlyCosts?: number;
    /** Transpiled from HypeProxy.Entities.ApplicationUsers.AuthorizationDetails */
    authorization?: AuthorizationDetails;
}

