/* THIS (.ts) FILE IS GENERATED BY Tapper */
/* eslint-disable */
/* tslint:disable */
import { ComputeUnit } from './HypeProxy.Entities.Infrastructure';
import { Provider } from './HypeProxy.Entities';
import { IpRotation } from './HypeProxy.Entities.Features';
import { BaseEntityWithCustomFilter, BaseEntityWithPurchaseContext } from './HypeProxy.Infrastructure.Entities';

/** Transpiled from HypeProxy.Entities.Proxies.Credential */
export type Credential = {
    /** Transpiled from string? */
    username?: string;
    /** Transpiled from string? */
    password?: string;
    /** Transpiled from System.Collections.Generic.IEnumerable<string>? */
    authorizedIps?: string[];
} & BaseEntityWithCustomFilter;

/** Transpiled from HypeProxy.Entities.Proxies.Proxy */
export type Proxy = {
    /** Transpiled from string? */
    remoteEntrypoint?: string;
    /** Transpiled from string? */
    remoteHostname?: string;
    /** Transpiled from int */
    port: number;
    /** Transpiled from int */
    port2?: number;
    /** Transpiled from System.Guid */
    computeUnitId?: string;
    /** Transpiled from System.Guid */
    providerId: string;
    /** Transpiled from System.Guid */
    credentialId: string;
    /** Transpiled from string? */
    comment?: string;
    /** Transpiled from string? */
    interface?: string;
    /** Transpiled from string? */
    mainData?: string;
} & BaseEntityWithPurchaseContext;

