/* THIS (.ts) FILE IS GENERATED BY Tapper */
/* eslint-disable */
/* tslint:disable */
import { Product, Feature, Location, Provider } from './HypeProxy.Entities';

/** Transpiled from HypeProxy.Infrastructure.Joins.ProductFeature */
export type ProductFeature = {
    /** Transpiled from System.Guid */
    id: string;
    /** Transpiled from System.Guid */
    productId: string;
    /** Transpiled from HypeProxy.Entities.Product */
    product: Product;
    /** Transpiled from System.Guid */
    featureId: string;
    /** Transpiled from HypeProxy.Entities.Feature */
    feature: Feature;
}

/** Transpiled from HypeProxy.Infrastructure.Joins.ProductLocation */
export type ProductLocation = {
    /** Transpiled from System.Guid */
    id: string;
    /** Transpiled from System.Guid */
    productId: string;
    /** Transpiled from HypeProxy.Entities.Product */
    product: Product;
    /** Transpiled from System.Guid */
    locationId: string;
    /** Transpiled from HypeProxy.Entities.Location */
    location: Location;
}

/** Transpiled from HypeProxy.Infrastructure.Joins.ProductProvider */
export type ProductProvider = {
    /** Transpiled from System.Guid */
    id: string;
    /** Transpiled from System.Guid */
    productId: string;
    /** Transpiled from HypeProxy.Entities.Product */
    product: Product;
    /** Transpiled from System.Guid */
    providerId: string;
    /** Transpiled from HypeProxy.Entities.Provider */
    provider: Provider;
}

