/* THIS (.ts) FILE IS GENERATED BY Tapper */
/* eslint-disable */
/* tslint:disable */

/** Transpiled from HypeProxy.Errors.ApiError */
export type ApiError = {
    /** Transpiled from string */
    code: string;
    /** Transpiled from string? */
    description?: string;
}

