/* THIS (.ts) FILE IS GENERATED BY Tapper */
/* eslint-disable */
/* tslint:disable */

/** Transpiled from HypeProxy.DataModels.GeolocationDetails */
export type GeolocationDetails = {
    /** Transpiled from string? */
    continent?: string;
    /** Transpiled from string? */
    country?: string;
    /** Transpiled from string? */
    countryCode?: string;
    /** Transpiled from string? */
    countryEmoji?: string;
    /** Transpiled from string? */
    region?: string;
    /** Transpiled from string? */
    city?: string;
}

