/* THIS (.ts) FILE IS GENERATED BY Tapper */
/* eslint-disable */
/* tslint:disable */
import { TicketPriorities } from './HypeProxy.Constants';
import { Purchase, BaseEntityWithOwnership, BaseEntityWithCustomFilter } from './HypeProxy.Entities';
import { User } from './HypeProxy.Entities.Users';

/** Transpiled from HypeProxy.Entities.Tickets.Ticket */
export type Ticket = {
    /** Transpiled from string */
    subject: string;
    /** Transpiled from HypeProxy.Constants.TicketPriorities */
    priority: TicketPriorities;
    /** Transpiled from string? */
    category?: string;
    /** Transpiled from string */
    message: string;
    /** Transpiled from bool */
    isClosed: boolean;
} & BaseEntityWithOwnership;

/** Transpiled from HypeProxy.Entities.Tickets.TicketAnswer */
export type TicketAnswer = {
    /** Transpiled from System.Guid */
    id: string;
    /** Transpiled from string */
    message: string;
    /** Transpiled from System.DateTime */
    answeredAt?: (Date | string);
    /** Transpiled from System.Guid */
    userId: string;
} & BaseEntityWithCustomFilter;

