/* THIS (.ts) FILE IS GENERATED BY Tapper */
/* eslint-disable */
/* tslint:disable */
import { AuthorizationDetails } from './HypeProxy.Entities.ApplicationUser';

/** Transpiled from HypeProxy.Responses.ApiKeyArtifact */
export type ApiKeyArtifact = {
    /** Transpiled from System.Guid */
    userId: string;
    /** Transpiled from string */
    token?: string;
    /** Transpiled from System.DateTime */
    tokenExpiration?: (Date | string);
}

/** Transpiled from HypeProxy.Responses.InsightsSummary */
export type InsightsSummary = {
    /** Transpiled from string */
    remoteIp?: string;
    /** Transpiled from HypeProxy.Responses.LocationDetails */
    geolocationDetails?: LocationDetails;
}

/** Transpiled from HypeProxy.Responses.LocationDetails */
export type LocationDetails = {
    /** Transpiled from string */
    continent?: string;
    /** Transpiled from string */
    country?: string;
    /** Transpiled from string */
    countryCode?: string;
    /** Transpiled from string */
    city?: string;
}

/** Transpiled from HypeProxy.Responses.OrderSummary */
export type OrderSummary = {
    /** Transpiled from string */
    details?: string;
    /** Transpiled from double */
    unitPrice: number;
    /** Transpiled from double */
    vatAmount?: number;
    /** Transpiled from double */
    subtotalAmount: number;
    /** Transpiled from double */
    totalAmount: number;
    /** Transpiled from string? */
    couponCode?: string;
    /** Transpiled from double */
    priceOff?: number;
    /** Transpiled from double */
    percentOff?: number;
    /** Transpiled from int */
    availableStockForCriteria: number;
}

/** Transpiled from HypeProxy.Responses.PaymentResponse */
export type PaymentResponse = {
    /** Transpiled from System.Uri */
    returnUrl?: string;
    /** Transpiled from string */
    customData?: string;
}

/** Transpiled from HypeProxy.Responses.PingResponse */
export type PingResponse = {
    /** Transpiled from bool */
    isOperational: boolean;
    /** Transpiled from int */
    reason: number;
    /** Transpiled from long */
    elapsedMilliseconds: number;
}

/** Transpiled from HypeProxy.Responses.RequestDetails */
export type RequestDetails = {
    /** Transpiled from System.Guid */
    id: string;
    /** Transpiled from System.Guid */
    userId?: string;
    /** Transpiled from string */
    endpoint?: string;
    /** Transpiled from System.DateTime */
    date: (Date | string);
    /** Transpiled from long */
    timestamp: number;
    /** Transpiled from string */
    userAgent?: string;
    /** Transpiled from string */
    clientIp?: string;
}

/** Transpiled from HypeProxy.Responses.UserRequirements */
export type UserRequirements = {
    /** Transpiled from System.Guid */
    id: string;
    /** Transpiled from bool */
    hadFirstLogin: boolean;
    /** Transpiled from bool */
    requireOnboarding: boolean;
    /** Transpiled from bool */
    requireKyc: boolean;
    /** Transpiled from bool */
    hasConfirmedEmail: boolean;
    /** Transpiled from bool */
    hasDefinedBillingDetails: boolean;
    /** Transpiled from bool */
    hasDefinedUsageExplanation: boolean;
    /** Transpiled from bool */
    hasAppliedKyc: boolean;
}

/** Transpiled from HypeProxy.Responses.UserSummary */
export type UserSummary = {
    /** Transpiled from System.Guid */
    userId: string;
    /** Transpiled from string */
    fullName?: string;
    /** Transpiled from string */
    avatar?: string;
    /** Transpiled from long */
    monthlyCosts?: number;
    /** Transpiled from HypeProxy.Entities.ApplicationUser.AuthorizationDetails */
    authorization?: AuthorizationDetails;
}

