/* THIS (.ts) FILE IS GENERATED BY Tapper */
/* eslint-disable */
/* tslint:disable */

/** Transpiled from HypeProxy.DataModels.LocationDetails */
export type LocationDetails = {
    /** Transpiled from string */
    continent?: string;
    /** Transpiled from string */
    country?: string;
    /** Transpiled from string */
    countryCode?: string;
    /** Transpiled from string */
    countryEmoji?: string;
    /** Transpiled from string */
    region?: string;
    /** Transpiled from string */
    city?: string;
}

/** Transpiled from HypeProxy.DataModels.LogLine */
export type LogLine = {
    /** Transpiled from System.DateTime */
    dateTime: (Date | string);
    /** Transpiled from string */
    serviceName?: string;
    /** Transpiled from int */
    errorCode: number;
    /** Transpiled from string */
    clientEndpoint?: string;
    /** Transpiled from string */
    targetEndpoint?: string;
    /** Transpiled from HypeProxy.DataModels.LocationDetails */
    clientLocation?: LocationDetails;
    /** Transpiled from HypeProxy.DataModels.LocationDetails */
    targetLocation?: LocationDetails;
    /** Transpiled from string */
    httpMethod?: string;
    /** Transpiled from string */
    url?: string;
    /** Transpiled from long */
    receivedBytes: number;
}

