/* THIS (.ts) FILE IS GENERATED BY Tapper */
/* eslint-disable */
/* tslint:disable */
import { BillingPeriods, PaymentMethods, TicketPriorities } from './HypeProxy.Constants';

/** Transpiled from HypeProxy.Dtos.ChangeBillingDetailsModel */
export type ChangeBillingDetailsModel = {
    /** Transpiled from string */
    fullName?: string;
    /** Transpiled from string */
    address?: string;
    /** Transpiled from string */
    zipCode?: string;
    /** Transpiled from string */
    city?: string;
    /** Transpiled from string */
    country?: string;
    /** Transpiled from bool */
    isCompany: boolean;
    /** Transpiled from string */
    companyName?: string;
    /** Transpiled from string */
    companyIdentificationNumber?: string;
    /** Transpiled from string */
    companyVatNumber?: string;
    /** Transpiled from string */
    companyCountry?: string;
}

/** Transpiled from HypeProxy.Dtos.ChangePasswordModel */
export type ChangePasswordModel = {
    /** Transpiled from string */
    currentPassword?: string;
    /** Transpiled from string */
    newPassword?: string;
    /** Transpiled from string */
    passwordConfirmation?: string;
}

/** Transpiled from HypeProxy.Dtos.ChangeRequirementsModel */
export type ChangeRequirementsModel = {
    /** Transpiled from string */
    usageDomain?: string;
    /** Transpiled from string */
    usageExplanation?: string;
}

/** Transpiled from HypeProxy.Dtos.ChangeUserSettingsModel */
export type ChangeUserSettingsModel = {
    /** Transpiled from HypeProxy.Constants.BillingPeriods */
    defaultBillingPeriods: BillingPeriods;
    /** Transpiled from HypeProxy.Constants.PaymentMethods */
    defaultPaymentMethods: PaymentMethods;
}

/** Transpiled from HypeProxy.Dtos.ConfirmEmailModel */
export type ConfirmEmailModel = {
    /** Transpiled from string */
    email?: string;
    /** Transpiled from string */
    token?: string;
}

/** Transpiled from HypeProxy.Dtos.CreateReminderModel */
export type CreateReminderModel = {
    /** Transpiled from string */
    email?: string;
    /** Transpiled from System.Guid */
    productId: string;
}

/** Transpiled from HypeProxy.Dtos.CreateTicketAnswerModel */
export type CreateTicketAnswerModel = {
    /** Transpiled from string */
    message?: string;
}

/** Transpiled from HypeProxy.Dtos.CreateTicketModel */
export type CreateTicketModel = {
    /** Transpiled from string */
    subject?: string;
    /** Transpiled from string */
    message?: string;
    /** Transpiled from HypeProxy.Constants.TicketPriorities */
    priority: TicketPriorities;
    /** Transpiled from System.Guid */
    relatedPurchaseId?: string;
}

/** Transpiled from HypeProxy.Dtos.ForgotPasswordModel */
export type ForgotPasswordModel = {
    /** Transpiled from string */
    email?: string;
}

/** Transpiled from HypeProxy.Dtos.OrderCriteria */
export type OrderCriteria = {
    /** Transpiled from System.Guid */
    productId: string;
    /** Transpiled from System.Guid */
    locationId: string;
    /** Transpiled from System.Guid */
    providerId: string;
    /** Transpiled from HypeProxy.Constants.PaymentMethods */
    paymentMethod: PaymentMethods;
    /** Transpiled from HypeProxy.Constants.BillingPeriods */
    billingPeriod: BillingPeriods;
    /** Transpiled from int */
    quantity: number;
    /** Transpiled from string? */
    couponCode?: string;
    /** Transpiled from bool */
    isAutomaticallyRenewed: boolean;
}

/** Transpiled from HypeProxy.Dtos.ResetPasswordModel */
export type ResetPasswordModel = {
    /** Transpiled from string */
    email?: string;
    /** Transpiled from string */
    token?: string;
    /** Transpiled from string */
    newPassword?: string;
    /** Transpiled from string */
    passwordConfirmation?: string;
}

/** Transpiled from HypeProxy.Dtos.SignInModel */
export type SignInModel = {
    /** Transpiled from string */
    email: string;
    /** Transpiled from string */
    password: string;
    /** Transpiled from string? */
    otpCode?: string;
}

/** Transpiled from HypeProxy.Dtos.SignUpModel */
export type SignUpModel = {
    /** Transpiled from string */
    email?: string;
    /** Transpiled from string */
    password?: string;
    /** Transpiled from string */
    fullname?: string;
    /** Transpiled from string */
    fingerprint?: string;
    /** Transpiled from bool */
    acceptTerms: boolean;
}

/** Transpiled from HypeProxy.Dtos.UpdateCommentModel */
export type UpdateCommentModel = {
    /** Transpiled from string */
    message?: string;
}

/** Transpiled from HypeProxy.Dtos.UpdateCredentialsModel */
export type UpdateCredentialsModel = {
    /** Transpiled from string */
    username?: string;
    /** Transpiled from string */
    password?: string;
    /** Transpiled from bool */
    isIpAuthenticationEnabled: boolean;
    /** Transpiled from string */
    authorizedIp?: string;
}

