/* THIS (.ts) FILE IS GENERATED BY Tapper */
/* eslint-disable */
/* tslint:disable */

/** Transpiled from HypeProxy.Responses.InsightsSummary.InsightsSummary */
export type InsightsSummary = {
    /** Transpiled from string */
    remoteIp?: string;
    /** Transpiled from HypeProxy.Responses.InsightsSummary.LocationDetails */
    geolocationDetails?: LocationDetails;
}

/** Transpiled from HypeProxy.Responses.InsightsSummary.LocationDetails */
export type LocationDetails = {
    /** Transpiled from string */
    continent?: string;
    /** Transpiled from string */
    country?: string;
    /** Transpiled from string */
    countryCode?: string;
    /** Transpiled from string */
    city?: string;
}

