/* THIS (.ts) FILE IS GENERATED BY Tapper */
/* eslint-disable */
/* tslint:disable */
import { Proxy } from './HypeProxy.Entities.Proxies';
import { BaseEntityWithCustomFilter } from './HypeProxy.Entities';

/** Transpiled from HypeProxy.Entities.Features.IpRotation */
export type IpRotation = {
    /** Transpiled from double */
    interval: number;
} & BaseEntityWithCustomFilter;

