/* THIS (.ts) FILE IS GENERATED BY Tapper */
/* eslint-disable */
/* tslint:disable */

/** Transpiled from HypeProxy.Errors.ApiError */
export type ApiError = {
    /** Transpiled from HypeProxy.Errors.ApiErrorCode */
    code: ApiErrorCode;
    /** Transpiled from string */
    description: string;
}

/** Transpiled from HypeProxy.Errors.ApiErrorCode */
export type ApiErrorCode = {
}

