/* THIS (.ts) FILE IS GENERATED BY Tapper */
/* eslint-disable */
/* tslint:disable */
import { InvoiceStatuses, PaymentMethods } from './HypeProxy.Constants';
import { Purchase, BaseEntityWithOwnership } from './HypeProxy.Entities';

/** Transpiled from HypeProxy.Entities.Invoices.Invoice */
export type Invoice = {
    /** Transpiled from HypeProxy.Constants.InvoiceStatuses */
    status: InvoiceStatuses;
    /** Transpiled from HypeProxy.Constants.PaymentMethods */
    paymentMethod: PaymentMethods;
    /** Transpiled from decimal */
    subtotalAmount: number;
    /** Transpiled from decimal */
    totalAmount: number;
    /** Transpiled from string? */
    thirdPartyInvoiceId?: string;
    /** Transpiled from string? */
    hostedInvoiceUrl?: string;
    /** Transpiled from string? */
    hostedInvoicePdfUrl?: string;
    /** Transpiled from System.Guid */
    purchaseId: string;
    /** Transpiled from System.Collections.Generic.ICollection<HypeProxy.Entities.Invoices.InvoiceItem>? */
    items?: InvoiceItem[];
} & BaseEntityWithOwnership;

/** Transpiled from HypeProxy.Entities.Invoices.InvoiceItem */
export type InvoiceItem = {
    /** Transpiled from System.Guid */
    id: string;
    /** Transpiled from string */
    name: string;
    /** Transpiled from int */
    quantity: number;
    /** Transpiled from decimal */
    unitPrice: number;
    /** Transpiled from decimal */
    totalAmount: number;
    /** Transpiled from System.Guid */
    invoiceId: string;
    /** Transpiled from HypeProxy.Entities.Invoices.Invoice */
    invoice: Invoice;
}

