/* THIS (.ts) FILE IS GENERATED BY Tapper */
/* eslint-disable */
/* tslint:disable */

/** Transpiled from HypeProxy.Responses.Insights.Summary.InsightsSummary */
export type InsightsSummary = {
    /** Transpiled from string */
    remoteIp?: string;
    /** Transpiled from string */
    internetServiceProvider?: string;
    /** Transpiled from string */
    asn?: string;
    /** Transpiled from int */
    trustScore: number;
    /** Transpiled from HypeProxy.Responses.Insights.Summary.LocationDetails */
    geolocationDetails?: LocationDetails;
}

/** Transpiled from HypeProxy.Responses.Insights.Summary.LocationDetails */
export type LocationDetails = {
    /** Transpiled from string */
    continent?: string;
    /** Transpiled from string */
    country?: string;
    /** Transpiled from string */
    countryCode?: string;
    /** Transpiled from string */
    countryEmoji?: string;
    /** Transpiled from string */
    region?: string;
    /** Transpiled from string */
    city?: string;
}

