/* THIS (.ts) FILE IS GENERATED BY Tapper */
/* eslint-disable */
/* tslint:disable */
import { PaymentMethods, BillingCycles, TicketPriorities } from './HypeProxy.Constants';

/** Transpiled from HypeProxy.Requests.ConfirmEmailRequest */
export type ConfirmEmailRequest = {
    /** Transpiled from string */
    email: string;
    /** Transpiled from string */
    token: string;
}

/** Transpiled from HypeProxy.Requests.CreateMemoRequest */
export type CreateMemoRequest = {
    /** Transpiled from string */
    message: string;
}

/** Transpiled from HypeProxy.Requests.CreatePurchaseRequest */
export type CreatePurchaseRequest = {
    /** Transpiled from System.Guid */
    productId: string;
    /** Transpiled from System.Guid */
    locationId: string;
    /** Transpiled from System.Guid */
    providerId: string;
    /** Transpiled from HypeProxy.Constants.PaymentMethods */
    paymentMethod: PaymentMethods;
    /** Transpiled from HypeProxy.Constants.BillingCycles */
    billingCycle: BillingCycles;
    /** Transpiled from int */
    quantity: number;
    /** Transpiled from string? */
    couponCode?: string;
    /** Transpiled from bool */
    isAutomaticallyRenewed: boolean;
}

/** Transpiled from HypeProxy.Requests.CreateReminderRequest */
export type CreateReminderRequest = {
    /** Transpiled from string? */
    email?: string;
    /** Transpiled from System.Guid */
    productId: string;
    /** Transpiled from System.Guid */
    locationId: string;
    /** Transpiled from System.Guid */
    providerId: string;
}

/** Transpiled from HypeProxy.Requests.CreateTicketAnswerRequest */
export type CreateTicketAnswerRequest = {
    /** Transpiled from string */
    message: string;
}

/** Transpiled from HypeProxy.Requests.CreateTicketRequest */
export type CreateTicketRequest = {
    /** Transpiled from string */
    subject: string;
    /** Transpiled from string */
    message: string;
    /** Transpiled from HypeProxy.Constants.TicketPriorities */
    priority: TicketPriorities;
    /** Transpiled from System.Guid */
    relatedPurchaseId?: string;
}

/** Transpiled from HypeProxy.Requests.DeletePurchaseRequest */
export type DeletePurchaseRequest = {
    /** Transpiled from string? */
    cancellationReason?: string;
    /** Transpiled from bool */
    claimRefund: boolean;
}

/** Transpiled from HypeProxy.Requests.ForgotPasswordRequest */
export type ForgotPasswordRequest = {
    /** Transpiled from string */
    email: string;
}

/** Transpiled from HypeProxy.Requests.PatchIpRotationRequest */
export type PatchIpRotationRequest = {
    /** Transpiled from int */
    interval: number;
}

/** Transpiled from HypeProxy.Requests.PatchProxyRequest */
export type PatchProxyRequest = {
    /** Transpiled from string */
    comment: string;
}

/** Transpiled from HypeProxy.Requests.PatchPurchaseRequest */
export type PatchPurchaseRequest = {
    /** Transpiled from HypeProxy.Constants.PaymentMethods */
    paymentMethod?: PaymentMethods;
    /** Transpiled from HypeProxy.Constants.BillingCycles */
    billingCycle?: BillingCycles;
    /** Transpiled from bool */
    isAutomaticallyRenewed: boolean;
    /** Transpiled from int */
    cyclesQuantity: number;
}

/** Transpiled from HypeProxy.Requests.ResetPasswordRequest */
export type ResetPasswordRequest = {
    /** Transpiled from string */
    email: string;
    /** Transpiled from string */
    token: string;
    /** Transpiled from string */
    newPassword: string;
}

/** Transpiled from HypeProxy.Requests.SignInRequest */
export type SignInRequest = {
    /** Transpiled from string */
    email: string;
    /** Transpiled from string */
    password: string;
}

/** Transpiled from HypeProxy.Requests.SignUpRequest */
export type SignUpRequest = {
    /** Transpiled from string */
    email: string;
    /** Transpiled from string */
    password: string;
    /** Transpiled from string */
    fullname: string;
    /** Transpiled from string */
    fingerprint: string;
    /** Transpiled from bool */
    acceptTerms: boolean;
}

/** Transpiled from HypeProxy.Requests.UpdateBillingDetailsRequest */
export type UpdateBillingDetailsRequest = {
    /** Transpiled from string */
    fullName: string;
    /** Transpiled from string */
    address: string;
    /** Transpiled from string */
    zipCode: string;
    /** Transpiled from string */
    city: string;
    /** Transpiled from string */
    country: string;
    /** Transpiled from bool */
    isCompany: boolean;
    /** Transpiled from string? */
    companyName?: string;
    /** Transpiled from string? */
    companyIdentificationNumber?: string;
    /** Transpiled from string? */
    companyVatNumber?: string;
    /** Transpiled from string? */
    companyCountry?: string;
}

/** Transpiled from HypeProxy.Requests.UpdateCredentialRequest */
export type UpdateCredentialRequest = {
    /** Transpiled from string */
    username: string;
    /** Transpiled from string */
    password: string;
    /** Transpiled from System.Collections.Generic.IEnumerable<string>? */
    authorizedIps?: string[];
}

/** Transpiled from HypeProxy.Requests.UpdatePasswordRequest */
export type UpdatePasswordRequest = {
    /** Transpiled from string */
    currentPassword: string;
    /** Transpiled from string */
    newPassword: string;
    /** Transpiled from string */
    passwordConfirmation: string;
}

/** Transpiled from HypeProxy.Requests.UpdateRequirementsRequest */
export type UpdateRequirementsRequest = {
    /** Transpiled from string */
    usageDomain: string;
    /** Transpiled from string */
    usageExplanation: string;
}

/** Transpiled from HypeProxy.Requests.UpdateSettingsRequest */
export type UpdateSettingsRequest = {
    /** Transpiled from bool */
    developerMode?: boolean;
    /** Transpiled from bool */
    betaEnrolled?: boolean;
    /** Transpiled from bool */
    skipPurchaseAssistant?: boolean;
    /** Transpiled from HypeProxy.Constants.BillingCycles */
    defaultBillingCycle?: BillingCycles;
    /** Transpiled from HypeProxy.Constants.PaymentMethods */
    defaultPaymentMethod?: PaymentMethods;
}

