/* THIS (.ts) FILE IS GENERATED BY Tapper */
/* eslint-disable */
/* tslint:disable */
import { InvoiceStatuses, PaymentMethods, WarningLevels, Icons, BillingPeriods, PurchaseStatuses, TicketPriorities } from './HypeProxy.Constants';
import { BillingDetails } from './HypeProxy.Entities.ApplicationUser';

/** Transpiled from HypeProxy.Entities.BaseEntity */
export type BaseEntity = {
    /** Transpiled from System.Guid */
    id: string;
    /** Transpiled from System.Guid */
    owner?: string;
    /** Transpiled from System.DateTime */
    creationDateTime?: (Date | string);
    /** Transpiled from System.DateTime */
    lastUpdateDateTime?: (Date | string);
    /** Transpiled from bool */
    isFeatured?: boolean;
    /** Transpiled from bool */
    isAllowed?: boolean;
    /** Transpiled from int */
    weight?: number;
    /** Transpiled from string? */
    contextData?: string;
    /** Transpiled from string? */
    customData?: string;
    /** Transpiled from bool */
    isNew: boolean;
}

/** Transpiled from HypeProxy.Entities.Bay */
export type Bay = {
    /** Transpiled from string */
    name?: string;
    /** Transpiled from System.Guid */
    productId: string;
    /** Transpiled from System.Guid */
    locationId: string;
} & BaseEntity;

/** Transpiled from HypeProxy.Entities.Coupon */
export type Coupon = {
    /** Transpiled from string */
    name?: string;
    /** Transpiled from string */
    description?: string;
    /** Transpiled from bool */
    isOneTime: boolean;
    /** Transpiled from bool */
    isUsed: boolean;
    /** Transpiled from double */
    percentOff: number;
    /** Transpiled from System.DateTime */
    expirationDateTime?: (Date | string);
} & BaseEntity;

/** Transpiled from HypeProxy.Entities.Credential */
export type Credential = {
    /** Transpiled from string */
    username?: string;
    /** Transpiled from string */
    password?: string;
    /** Transpiled from bool */
    isIpAuthenticationEnabled: boolean;
    /** Transpiled from string? */
    authorizedIp?: string;
    /** Transpiled from bool */
    isHttpEnabled: boolean;
    /** Transpiled from bool */
    isSocksEnabled: boolean;
} & BaseEntity;

/** Transpiled from HypeProxy.Entities.Feature */
export type Feature = {
    /** Transpiled from string */
    tag?: string;
    /** Transpiled from string */
    name?: string;
    /** Transpiled from string */
    description?: string;
    /** Transpiled from string */
    icon?: string;
    /** Transpiled from string */
    frontComponentName?: string;
    /** Transpiled from string */
    bladeComponentName?: string;
    /** Transpiled from string */
    extraComponentName?: string;
} & BaseEntity;

/** Transpiled from HypeProxy.Entities.FeatureProduct */
export type FeatureProduct = {
    /** Transpiled from System.Guid */
    featureId: string;
    /** Transpiled from System.Guid */
    productId: string;
} & BaseEntity;

/** Transpiled from HypeProxy.Entities.Invoice */
export type Invoice = {
    /** Transpiled from System.Guid */
    productId: string;
    /** Transpiled from System.Guid */
    purchaseId: string;
    /** Transpiled from HypeProxy.Constants.InvoiceStatuses */
    status: InvoiceStatuses;
    /** Transpiled from HypeProxy.Constants.PaymentMethods */
    paymentMethod: PaymentMethods;
    /** Transpiled from HypeProxy.Entities.ApplicationUser.BillingDetails */
    billingDetails?: BillingDetails;
    /** Transpiled from int */
    itemQuantity: number;
    /** Transpiled from double */
    unitPrice: number;
    /** Transpiled from double */
    vatAmount?: number;
    /** Transpiled from double */
    subtotalAmount: number;
    /** Transpiled from double */
    totalAmount: number;
    /** Transpiled from string? */
    couponCode?: string;
    /** Transpiled from double */
    priceOff?: number;
    /** Transpiled from double */
    percentOff?: number;
    /** Transpiled from string */
    thirdPartyInvoiceId?: string;
    /** Transpiled from string */
    hostedInvoiceUrl?: string;
    /** Transpiled from string */
    hostedInvoicePdfUrl?: string;
    /** Transpiled from string */
    itemName?: string;
    /** Transpiled from string */
    details?: string;
} & BaseEntity;

/** Transpiled from HypeProxy.Entities.IpRotation */
export type IpRotation = {
    /** Transpiled from System.Guid */
    proxyId: string;
    /** Transpiled from int */
    interval: number;
    /** Transpiled from bool */
    isEnabled: boolean;
} & BaseEntity;

/** Transpiled from HypeProxy.Entities.Location */
export type Location = {
    /** Transpiled from string */
    name?: string;
    /** Transpiled from string */
    city?: string;
    /** Transpiled from string */
    region?: string;
    /** Transpiled from string */
    country?: string;
    /** Transpiled from string */
    countryCode?: string;
    /** Transpiled from string */
    flagUrl?: string;
    /** Transpiled from int */
    availableStock: number;
    /** Transpiled from bool */
    outOfStock: boolean;
} & BaseEntity;

/** Transpiled from HypeProxy.Entities.LocationProduct */
export type LocationProduct = {
    /** Transpiled from System.Guid */
    locationId: string;
    /** Transpiled from System.Guid */
    productId: string;
} & BaseEntity;

/** Transpiled from HypeProxy.Entities.Memo */
export type Memo = {
    /** Transpiled from string */
    message?: string;
} & BaseEntity;

/** Transpiled from HypeProxy.Entities.Notification */
export type Notification = {
    /** Transpiled from string */
    title?: string;
    /** Transpiled from string */
    message?: string;
    /** Transpiled from HypeProxy.Constants.WarningLevels */
    level: WarningLevels;
    /** Transpiled from HypeProxy.Constants.Icons */
    icon: Icons;
    /** Transpiled from bool */
    isSeen: boolean;
} & BaseEntity;

/** Transpiled from HypeProxy.Entities.Product */
export type Product = {
    /** Transpiled from string */
    name?: string;
    /** Transpiled from string */
    shortName?: string;
    /** Transpiled from string */
    tagline?: string;
    /** Transpiled from string */
    label?: string;
    /** Transpiled from string */
    description?: string;
    /** Transpiled from string */
    cardDescription?: string;
    /** Transpiled from string */
    htmlContent?: string;
    /** Transpiled from string */
    icon?: string;
    /** Transpiled from string */
    illustrationUrl?: string;
    /** Transpiled from System.Collections.Generic.IEnumerable<HypeProxy.Constants.BillingPeriods> */
    availableBillingPeriods?: BillingPeriods[];
    /** Transpiled from int */
    minimumOrder?: number;
    /** Transpiled from string? */
    preHook?: string;
    /** Transpiled from string? */
    postHook?: string;
} & BaseEntity;

/** Transpiled from HypeProxy.Entities.Provider */
export type Provider = {
    /** Transpiled from string */
    name?: string;
    /** Transpiled from string */
    description?: string;
    /** Transpiled from string */
    companyName?: string;
    /** Transpiled from string */
    websiteUrl?: string;
    /** Transpiled from string */
    logoUrl?: string;
    /** Transpiled from int */
    availableStock: number;
    /** Transpiled from bool */
    outOfStock: boolean;
} & BaseEntity;

/** Transpiled from HypeProxy.Entities.ProviderLocation */
export type ProviderLocation = {
    /** Transpiled from System.Guid */
    providerId: string;
    /** Transpiled from System.Guid */
    locationId: string;
} & BaseEntity;

/** Transpiled from HypeProxy.Entities.Proxy */
export type Proxy = {
    /** Transpiled from System.Guid */
    productId: string;
    /** Transpiled from System.Guid */
    locationId: string;
    /** Transpiled from System.Guid */
    bayId: string;
    /** Transpiled from System.Guid */
    providerId: string;
    /** Transpiled from System.Guid */
    credentialsId: string;
    /** Transpiled from string */
    remoteEndpoint?: string;
    /** Transpiled from string */
    remoteHostname?: string;
    /** Transpiled from int */
    port: number;
    /** Transpiled from int */
    port2?: number;
    /** Transpiled from bool */
    isAvailable: boolean;
    /** Transpiled from string */
    comment?: string;
    /** Transpiled from string */
    interface?: string;
    /** Transpiled from string */
    mainData?: string;
} & BaseEntity;

/** Transpiled from HypeProxy.Entities.Purchase */
export type Purchase = {
    /** Transpiled from System.Guid */
    productId: string;
    /** Transpiled from System.DateTime */
    startDateTime: (Date | string);
    /** Transpiled from System.DateTime */
    endDateTime: (Date | string);
    /** Transpiled from System.Collections.Generic.IEnumerable<System.Guid> */
    content?: string[];
    /** Transpiled from HypeProxy.Constants.PurchaseStatuses */
    status: PurchaseStatuses;
    /** Transpiled from HypeProxy.Constants.PaymentMethods */
    paymentMethod: PaymentMethods;
    /** Transpiled from HypeProxy.Constants.BillingPeriods */
    billingPeriod: BillingPeriods;
    /** Transpiled from string? */
    relatedPaymentId?: string;
    /** Transpiled from System.Guid */
    couponId?: string;
    /** Transpiled from bool */
    isAutomaticallyRenewed: boolean;
    /** Transpiled from bool */
    isTrial: boolean;
    /** Transpiled from bool */
    isRenewable: boolean;
    /** Transpiled from bool */
    isGracePeriod: boolean;
    /** Transpiled from System.DateTime */
    gracePeriodStartDateTime: (Date | string);
} & BaseEntity;

/** Transpiled from HypeProxy.Entities.Reminder */
export type Reminder = {
    /** Transpiled from System.Guid */
    productId: string;
    /** Transpiled from System.Guid */
    locationId?: string;
    /** Transpiled from System.Guid */
    providerId?: string;
    /** Transpiled from string */
    contactEmail?: string;
    /** Transpiled from bool */
    wasContacted: boolean;
} & BaseEntity;

/** Transpiled from HypeProxy.Entities.Ticket */
export type Ticket = {
    /** Transpiled from string */
    subject?: string;
    /** Transpiled from HypeProxy.Constants.TicketPriorities */
    priority: TicketPriorities;
    /** Transpiled from string */
    category?: string;
    /** Transpiled from string */
    message?: string;
    /** Transpiled from System.Guid */
    relatedPurchaseId?: string;
    /** Transpiled from string? */
    attachmentUrl?: string;
    /** Transpiled from bool */
    isClosed: boolean;
} & BaseEntity;

/** Transpiled from HypeProxy.Entities.TicketAnswer */
export type TicketAnswer = {
    /** Transpiled from System.Guid */
    ticketId: string;
    /** Transpiled from string */
    message?: string;
    /** Transpiled from string? */
    attachmentUrl?: string;
} & BaseEntity;

