/* THIS (.ts) FILE IS GENERATED BY Tapper */
/* eslint-disable */
/* tslint:disable */
import { User } from './HypeProxy.Entities.Users';
import { Purchase } from './HypeProxy.Entities';

/** Transpiled from HypeProxy.Infrastructure.Entities.BaseEntity */
export type BaseEntity = {
    /** Transpiled from System.Guid */
    id: string;
    /** Transpiled from bool */
    isFeatured?: boolean;
    /** Transpiled from bool */
    isAllowed?: boolean;
    /** Transpiled from int */
    weight?: number;
}

/** Transpiled from HypeProxy.Infrastructure.Entities.BaseEntityWithCustomFilter */
export type BaseEntityWithCustomFilter = {
} & BaseEntity;

/** Transpiled from HypeProxy.Infrastructure.Entities.BaseEntityWithOwnership */
export type BaseEntityWithOwnership = {
    /** Transpiled from System.DateTime */
    createdAt?: (Date | string);
    /** Transpiled from System.DateTime */
    updatedAt?: (Date | string);
} & BaseEntity;

/** Transpiled from HypeProxy.Infrastructure.Entities.BaseEntityWithPurchaseContext */
export type BaseEntityWithPurchaseContext = {
    /** Transpiled from System.Guid */
    purchaseId?: string;
} & BaseEntity;

