/* THIS (.ts) FILE IS GENERATED BY Tapper */
/* eslint-disable */
/* tslint:disable */
import { BillingPeriods, PaymentMethods } from './HypeProxy.Constants';

/** Transpiled from HypeProxy.Entities.ApplicationUser.ApplicationUser */
export type ApplicationUser = {
    /** Transpiled from System.Guid */
    id: string;
    /** Transpiled from string */
    email?: string;
    /** Transpiled from string */
    fullName?: string;
    /** Transpiled from HypeProxy.Entities.ApplicationUser.BillingDetails */
    billingDetails?: BillingDetails;
    /** Transpiled from HypeProxy.Entities.ApplicationUser.ConfidenceDetails */
    confidenceDetails?: ConfidenceDetails;
    /** Transpiled from string */
    stripeCustomerId?: string;
    /** Transpiled from System.DateTime */
    registrationDateTime: (Date | string);
    /** Transpiled from string */
    cultureConcern?: string;
    /** Transpiled from int */
    securityFlag: number;
    /** Transpiled from string */
    passwordSignature?: string;
    /** Transpiled from string */
    fingerprintId?: string;
    /** Transpiled from HypeProxy.Entities.ApplicationUser.AuthorizationDetails */
    authorizationDetails?: AuthorizationDetails;
    /** Transpiled from HypeProxy.Entities.ApplicationUser.UserSettings */
    settings?: UserSettings;
    /** Transpiled from bool */
    hadFirstLogin: boolean;
    /** Transpiled from string */
    customData?: string;
}

/** Transpiled from HypeProxy.Entities.ApplicationUser.AuthorizationDetails */
export type AuthorizationDetails = {
    /** Transpiled from System.Guid */
    id: string;
    /** Transpiled from bool */
    isDenied: boolean;
    /** Transpiled from string */
    deniedReason?: string;
    /** Transpiled from System.DateTime */
    blockingDateTime?: (Date | string);
}

/** Transpiled from HypeProxy.Entities.ApplicationUser.BillingDetails */
export type BillingDetails = {
    /** Transpiled from System.Guid */
    id: string;
    /** Transpiled from bool */
    hasBillingDetailsDefined: boolean;
    /** Transpiled from string */
    address?: string;
    /** Transpiled from string */
    zipCode?: string;
    /** Transpiled from string */
    city?: string;
    /** Transpiled from string */
    country?: string;
    /** Transpiled from bool */
    isCompany: boolean;
    /** Transpiled from string */
    companyName?: string;
    /** Transpiled from string */
    companyIdentificationNumber?: string;
    /** Transpiled from string */
    companyVatNumber?: string;
    /** Transpiled from string */
    companyCountry?: string;
}

/** Transpiled from HypeProxy.Entities.ApplicationUser.ConfidenceDetails */
export type ConfidenceDetails = {
    /** Transpiled from System.Guid */
    id: string;
    /** Transpiled from bool */
    hasAppliedKyc: boolean;
    /** Transpiled from string */
    usageDomain?: string;
    /** Transpiled from string */
    usageExplanation?: string;
    /** Transpiled from string */
    kycId?: string;
}

/** Transpiled from HypeProxy.Entities.ApplicationUser.UserSettings */
export type UserSettings = {
    /** Transpiled from System.Guid */
    id: string;
    /** Transpiled from HypeProxy.Constants.BillingPeriods */
    defaultBillingPeriods?: BillingPeriods;
    /** Transpiled from HypeProxy.Constants.PaymentMethods */
    defaultPaymentMethods?: PaymentMethods;
}

